### ISSUE TITLE
Error when submitting fasta files

### ISSUE THREAD

**Issue by YairGatt** [boulund/phaster_scripts#2]
Hello,
This useful script worked well just a couple of weeks ago. But now I seem to get an odd error message when submitting fasta files:
"error: The sequence header is not on the first line. Please check!"

I get this even when submitting test files such as:
>header
_genomic sequence_

Do you know anything that might have changed?

Thank you for the great script,
Yair Gatt

**Comment by boulund** [comment]
Hi,

Sorry for my late reply! I didn't notice this issue had been filed until just now (I never got a notification for some reason?), and I didn't know anyone else actually had tried or used this script! :+1: 

I haven't used it much myself since I wrote it this summer. Perhaps they changed the API a bit. I'll have to investigate!

**Comment by boulund** [comment]
I looked into this a bit, and it appears the API endpoint works as it should. Something must have changed with the way the request is sent by the script. I will have to investigate further.

**Comment by YairGatt** [comment]
Thank you for your reply and effort.
For this project I wrote an alternative simple shell script. Nevertheless,
your script is of course much more effective and if it will work I will
surely use it in the future.
Best regards and thank again,
Yair Gatt

בתאריך יום ד׳, 14 בנוב׳ 2018, 9:57, מאת Fredrik Boulund <
notifications@github.com>:

**Comment by ash-bell** [comment]
Hi! I seem to have the same problem. The phaster_jobs.tsv file is also empty after submission. 

(base) [agb214@login02 phaster_scripts]$ ./phaster.py --fasta ../AAAA.reformatted.fasta 
2019-02-12 11:19:46,081 INFO: Submission of ../AAAA.reformatted.fasta appears successful
2019-02-12 11:19:46,082 INFO:   job_id: ZZ_b8c91de39e
2019-02-12 11:19:46,082 INFO:   error: The sequence header is not on the first line. Please check!
Traceback (most recent call last):
  File "./phaster.py", line 162, in <module>
    job_id, status, date = submit_job(fasta, options.url, {"contigs": int(options.contigs)})
  File "./phaster.py", line 99, in submit_job
    return r_dict["job_id"], r_dict["status"], datetime.datetime.now()
KeyError: 'status'

**Comment by boulund** [comment]
Yes, something has changed with how the API requests from my script are presented to the PHASTER API endpoint. It just doesn't work anymore and I haven't had any time to look into it. The API still appears to work if you make manual POST requests according to their instructions, but the code in my Python script does something wrong.

Sorry!

**Comment by boulund** [comment]
This should now be fixed, please reopen if not.
